# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hubviz_cpp <- function(data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_theta, jump_w, pr_mean_theta, pr_sd_theta, pr_mean_w, prior_a, prior_b, option = TRUE, cores = 1L) {
    .Call('_hubviz_hubviz_cpp', PACKAGE = 'hubviz', data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_theta, jump_w, pr_mean_theta, pr_sd_theta, pr_mean_w, prior_a, prior_b, option, cores)
}

